#cmmds to start the postgres db container
# sudo systemctl start docker
# sudo docker compose -f compose.yaml up -d
#  sudo docker stop  coupon-management-service-db-1
### to run the app as docker container (both postgre and app)
#sudo docker build -t coupon-service .
#sudo docker compose up -d
services:
  db:
    image: postgres
    restart: always
    volumes: #persistence volume for using the created tables and data on restart.
      - coupon-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=coupon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  coupon-service:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
volumes:
  coupon-db-data: