spring.application.name=coupon-management-service
CREATE TABLE coupons (
id UUID PRIMARY KEY,
code TEXT UNIQUE,
type TEXT NOT NULL,        -- ENUM
start_date TIMESTAMP,
end_date TIMESTAMP,
max_uses INT,
uses INT DEFAULT 0,
repetition_limit INT,
active BOOLEAN DEFAULT TRUE,
details JSONB NOT NULL,    -- store type-specific details
created_at TIMESTAMP DEFAULT now(),
updated_at TIMESTAMP DEFAULT now()
);
